# Generated by Django 2.2.3 on 2019-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='')),
                ('username', models.TextField(verbose_name='')),
                ('password', models.TextField(verbose_name='')),
                ('channels', models.ManyToManyField(to='bot.Channel', verbose_name='')),
            ],
        ),
    ]
