# Generated by Django 2.2.3 on 2019-07-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190715_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(verbose_name='Name of user who posted the message.')),
                ('datetime', models.DateTimeField(verbose_name='Date and time when message posted.')),
                ('text', models.TextField(verbose_name='Message text.')),
                ('link', models.TextField(unique=True, verbose_name='Unique message link.')),
            ],
        ),
    ]
